## Azure DevOps pipeline to create an AKS-HCI workload cluster using the repo script
## This template mirrors deploy-aks-hci.yml but uses token placeholders so bootstrap-and-build.ps1
## can render environment-specific pipelines.

trigger: none
pr: none

parameters:
  - name: InstanceNumber
    type: string
    default: "__INSTANCE_NUMBER__"
  - name: AutoApprove
    type: boolean
    default: true
  - name: LinuxNodeCount
    type: number
    default: 2
  - name: WindowsNodeCount
    type: number
    default: 2
  - name: LinuxVmSize
    type: string
    default: "Standard_D4s_v3"
    values:
      - "Standard_D2s_v3"
      - "Standard_D4s_v3"
      - "Standard_D8s_v3"
      - "Standard_D16s_v3"
  - name: WindowsVmSize
    type: string
    default: "Standard_D4s_v3"
    values:
      - "Standard_D2s_v3"
      - "Standard_D4s_v3"
      - "Standard_D8s_v3"
      - "Standard_D16s_v3"
  - name: DeleteCluster
    type: boolean
    default: false
  - name: windowsOnPremPoolName
    type: string
    default: "__WINDOWS_ONPREM_POOL_NAME__"

variables:
  - group: "__AZURE_DEVOPS_VARIABLE_GROUP__" # to get AZDO_PAT
  - name: InstanceNumber
    value: ${{ parameters.InstanceNumber }}
  - name: AutoApprove
    value: ${{ parameters.AutoApprove }}
  - name: LinuxNodeCount
    value: ${{ parameters.LinuxNodeCount }}
  - name: WindowsNodeCount
    value: ${{ parameters.WindowsNodeCount }}
  - name: LinuxVmSize
    value: ${{ parameters.LinuxVmSize }}
  - name: WindowsVmSize
    value: ${{ parameters.WindowsVmSize }}
  - name: DeleteCluster
    value: ${{ parameters.DeleteCluster }}

# Use a Windows agent so we can run Windows PowerShell 5.x
pool:
  name: "${{ parameters.windowsOnPremPoolName }}"

stages:
  - stage: deploy
    displayName: Deploy AKS-HCI Workload Cluster
    jobs:
      - job: deploy
        displayName: Create AKS-HCI Workload Cluster
        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: "Run Manage-AksHci-WorkloadCluster.ps1 (Windows PowerShell host)"
            inputs:
              targetType: "inline"
              # We launch Windows PowerShell (powershell.exe) explicitly so the script runs in PSv5
              script: |
                Write-Host "Preparing to run Manage-AksHci-WorkloadCluster.ps1 for instance $(InstanceNumber)"
                function Convert-ToBool {
                    param([string]$Value)
                    if ([string]::IsNullOrWhiteSpace($Value)) { return $false }
                    try { return [System.Convert]::ToBoolean($Value) }
                    catch { return $false }
                }

                $instance = '$(InstanceNumber)'
                $auto = Convert-ToBool '$(AutoApprove)'
                $linuxCount = [int]('$(LinuxNodeCount)')
                $windowsCount = [int]('$(WindowsNodeCount)')
                $linuxVmSize = '$(LinuxVmSize)'
                $windowsVmSize = '$(WindowsVmSize)'
                $delete = Convert-ToBool '$(DeleteCluster)'
                Write-Host "Resolved runtime flags: AutoApprove=$auto DeleteCluster=$delete"
                if ($delete) { Write-Host "DeleteCluster=true -> will skip kubeconfig upload task via condition" }

                # Write kubeconfig into the pipeline workspace so we can upload it to Azure DevOps secure files
                $kubeDir = Join-Path -Path '$(Pipeline.Workspace)' -ChildPath 'kubeconfigs'
                if (-not (Test-Path $kubeDir)) { New-Item -ItemType Directory -Path $kubeDir | Out-Null }
                $kubePath = Join-Path -Path $kubeDir -ChildPath ("workload-cluster-{0}-kubeconfig.yaml" -f $instance)

                $args = @('-NoProfile','-ExecutionPolicy','Bypass','-File','./infra/scripts/AzureLocal/Manage-AksHci-WorkloadCluster.ps1', '-InstanceNumber',$instance,'-LinuxNodeCount',$linuxCount,'-WindowsNodeCount',$windowsCount,'-KubeConfigPath',$kubePath)
                # Default to waiting for provisioning and collecting diagnostics on failure in CI runs
                $args += '-WaitForProvisioning','-ProvisioningTimeoutMinutes','40','-CollectDiagnosticsOnFailure'
                if ($linuxVmSize) { $args += '-LinuxNodeVmSize'; $args += $linuxVmSize }
                if ($windowsVmSize) { $args += '-WindowsNodeVmSize'; $args += $windowsVmSize }
                if ($auto) { $args += '-AutoApprove' }
                if ($delete) { $args += '-DeleteCluster' }

                Write-Host "Invoking Windows PowerShell with arguments: $($args -join ' ')"
                # Call desktop PowerShell directly so stdout/stderr streams to the pipeline in real time
                & 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe' @args
                $exit = $LASTEXITCODE
                if ($exit -ne 0) {
                    Write-Error "Manage-AksHci-WorkloadCluster.ps1 failed with exit code $exit"
                    exit $exit
                }

          - task: PowerShell@2
            # Skip upload if this is a delete run
            condition: and(succeeded(), ne(variables['DeleteCluster'], 'true'))
            displayName: "Upload kubeconfig to Azure DevOps secure files"
            inputs:
              targetType: "inline"
              script: |
                # Required pipeline variables (set these as pipeline secrets/variables in your pipeline):
                # $(SecureFilePAT) - Personal Access Token with permission to manage secure files
                # $(AzureDevOpsOrg) - your org (e.g., 'myorg' or 'https://dev.azure.com/myorg')
                # $(AzureDevOpsProjectID) - project id or name

                if (-not $env:SecureFilePAT) { Write-Error 'SecureFilePAT environment variable not set'; exit 1 }
                if (-not $env:AzureDevOpsOrg) { Write-Error 'AzureDevOpsOrg environment variable not set'; exit 1 }
                if (-not $env:AzureDevOpsProjectID) { Write-Error 'AzureDevOpsProjectID environment variable not set'; exit 1 }

                $instance = '$(InstanceNumber)'
                $kubePath = Join-Path -Path '$(Pipeline.Workspace)' -ChildPath ("kubeconfigs/workload-cluster-{0}-kubeconfig.yaml" -f $instance)
                if (-not (Test-Path $kubePath)) { Write-Error "Kubeconfig not found at $kubePath"; exit 2 }

                $secureName = "AKS_workload-cluster-{0}-kubeconfig_file-azurelocal" -f $instance
                Write-Host "Uploading $kubePath as secure file named $secureName"

                $uploadScript = 'scripts/upload-secure-file-rest.ps1'
                if (-not (Test-Path $uploadScript)) { Write-Error "Upload script not found: $uploadScript"; exit 3 }

                function Test-PlaceholderValue {
                    param([string]$Value)
                    if ([string]::IsNullOrWhiteSpace($Value)) { return $true }
                    return $Value -match '^\$\(.+\)$'
                }

                $resolvedOrg = $env:AzureDevOpsOrg
                if (Test-PlaceholderValue $resolvedOrg) {
                    $collectionUri = '$(System.CollectionUri)'
                    if ($collectionUri -match 'https://dev\.azure\.com/([^/]+)/?') {
                        $resolvedOrg = $Matches[1]
                        Write-Host "AzureDevOpsOrg not provided; using '$resolvedOrg' from System.CollectionUri."
                    }
                }

                if (Test-PlaceholderValue $resolvedOrg) {
                    Write-Error "AzureDevOpsOrg pipeline variable is not populated; set a real org name (e.g. 'myorg')."
                    exit 4
                }

                $resolvedProject = $env:AzureDevOpsProjectID
                if (Test-PlaceholderValue $resolvedProject) {
                    $resolvedProject = '$(System.TeamProjectId)'
                    if (-not (Test-PlaceholderValue $resolvedProject)) {
                        Write-Host "AzureDevOpsProjectID not provided; using project id '$resolvedProject'."
                    }
                }

                if (Test-PlaceholderValue $resolvedProject) {
                    Write-Error "AzureDevOpsProjectID pipeline variable is not populated; set the project ID or name."
                    exit 4
                }

                & pwsh -NoProfile -File $uploadScript -PAT $env:SecureFilePAT -AzureDevOpsOrg $resolvedOrg -AzureDevOpsProjectID $resolvedProject -SecureNameFile2Upload $secureName -SecureNameFilePath2Upload $kubePath
                if ($LASTEXITCODE -ne 0) {
                    Write-Error "Upload script failed with exit code $LASTEXITCODE"
                    exit $LASTEXITCODE
                }
            env:
              # Use AZDO_PAT from the variable group ADO_az-devops-agents-k8s
              SecureFilePAT: $(AZDO_PAT)
              AzureDevOpsOrg: $(AzureDevOpsOrg)
              AzureDevOpsProjectID: $(AzureDevOpsProjectID)

          - task: PublishPipelineArtifact@1
            displayName: "Publish logs/outputs (optional)"
            inputs:
              targetPath: "infra/scripts/AzureLocal"
              artifact: "aks-hci-scripts"
