# hello world pipeline
# This pipeline deploys an agent pool on AKS
# using the az-selfhosted-agents helm chart

trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  - group: ADO_k8s_agent_pool_vars

steps:
  - checkout: self
    persistCredentials: true
  # powershell script to list agent pools
  - task: PowerShell@2
    displayName: "List Agent Pools"
    inputs:
      filePath: "infra/scripts/New-KubernetesAgentPool.ps1"
      pwsh: true
    env:
      AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
