## Azure DevOps pipeline to deploy AKS + ACR using infra/bicep/deploy.ps1
## This pipeline uses the AzureCLI@2 task (PowerShell Core) so 'az' is available
## Fill in the 'azureSubscription' variable with your service connection name.

trigger: none
pr: none

parameters:
  - name: AZURE_SERVICE_CONNECTION
    type: string
    default: "__AZURE_SERVICE_CONNECTION__"
    values:
      - "__AZURE_SERVICE_CONNECTION__"
  - name: ACR_NAME
    type: string
    default: "__ACR_NAME__"
    values:
      - "__ACR_NAME__"
  - name: SkipContainerRegistry
    type: boolean
    default: __SKIP_CONTAINER_REGISTRY__
  - name: InstanceNumber
    type: string
    default: "__INSTANCE_NUMBER__"
  - name: DeleteResourceGroup
    type: boolean
    default: false
  - name: DeleteAksOnly
    type: boolean
    default: false
  - name: WindowsAdminUsername
    type: string
    default: "azureuser"

variables:
  - name: azureSubscription
    value: ${{ parameters.AZURE_SERVICE_CONNECTION }}
  - name: ACR_NAME
    value: ${{ parameters.ACR_NAME }}
  - name: SkipContainerRegistry
    value: ${{ parameters.SkipContainerRegistry }}
  - name: InstanceNumber
    value: ${{ parameters.InstanceNumber }}
  - name: ResourceGroupName
    value: ""
  - name: Location
    value: "canadacentral"
  - name: EnableWindows
    value: "true"
  - name: DeleteResourceGroup
    value: "${{ parameters.DeleteResourceGroup }}"
  - name: DeleteAksOnly
    value: "${{ parameters.DeleteAksOnly }}"
  - name: WindowsAdminUsername
    value: "${{ parameters.WindowsAdminUsername }}"
  # WindowsAdminPassword should be provided as a pipeline variable marked secret in Azure DevOps
  - name: WindowsAdminPassword
    value: ""
  - name: WindowsNodeCount
    value: "1"
  - name: LinuxNodeCount
    value: "1"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: deploy
    displayName: Deploy AKS + ACR
    jobs:
      - job: deploy
        displayName: Deploy
        steps:
          - checkout: self

          - task: AzureCLI@2
            displayName: "Deploy AKS and ACR (Bicep)"
            inputs:
              azureSubscription: "$(azureSubscription)"
              scriptType: "pscore"
              scriptLocation: "inlineScript"
              addSpnToEnvironment: true
              inlineScript: |
                Write-Host 'Running infra/bicep/deploy.ps1'
                $instanceNumber = '$(InstanceNumber)'
                $rg = '$(ResourceGroupName)'
                $location = '$(Location)'
                $enableWindows = ('$(EnableWindows)' -eq 'true')
                $winCount = [int]'$(WindowsNodeCount)'
                $linuxCount = [int]'$(LinuxNodeCount)'

                # Directly call the script with explicit named parameters so PowerShell receives typed values
                # Launch a separate pwsh process passing each argument explicitly. This avoids
                # Azure Pipelines' inline script quoting/expansion issues that can mangle args.
                $argList = @('-NoLogo','-NoProfile','-ExecutionPolicy','Bypass','-File','./infra/bicep/deploy.ps1',
                    '-InstanceNumber',$instanceNumber,'-Location',$location,'-WindowsNodeCount',$winCount,'-LinuxNodeCount',$linuxCount)
                if ($rg -and $rg -ne '') { $argList += @('-ResourceGroupName',$rg) }
                $argList += "-EnableWindows:$enableWindows"
                # If the pipeline requested skipping registry creation, forward that to the deploy script
                if ('$(SkipContainerRegistry)' -eq 'True') { $argList += '-SkipContainerRegistry' }
                # Pass optional delete flags and Windows admin credentials
                if ('$(DeleteResourceGroup)' -eq 'True') { $argList += '-DeleteResourceGroup' }
                if ('$(DeleteAksOnly)' -eq 'True') { $argList += '-DeleteAksOnly' }
                if ('$(WindowsAdminUsername)' -and '$(WindowsAdminUsername)' -ne '') { $argList += @('-WindowsAdminUsername','$(WindowsAdminUsername)') }
                # WindowsAdminPassword is a pipeline variable that should be marked secret in Azure DevOps; pass it as an argument (the pipeline masks secrets in logs)
                if ('$(WindowsAdminPassword)' -and '$(WindowsAdminPassword)' -ne '') { $argList += @('-WindowsAdminPassword','$(WindowsAdminPassword)') }

                Write-Host "Starting pwsh to run deploy.ps1 with args: $($argList -join ' ')"
                $proc = Start-Process pwsh -ArgumentList $argList -NoNewWindow -Wait -PassThru
                if ($proc.ExitCode -ne 0) {
                    Write-Error "deploy.ps1 failed with exit code $($proc.ExitCode)"
                    exit $proc.ExitCode
                }

          - task: PublishPipelineArtifact@1
            displayName: "Publish deployment outputs (optional)"
            inputs:
              targetPath: "infra/bicep"
              artifact: "bicep-deploy"
