# hello world pipeline
# This pipeline deploys an agent pool on AKS
# using the az-selfhosted-agents helm chart

trigger: none

pool:
  vmImage: "ubuntu-latest"

steps:
  - checkout: self
    persistCredentials: true
  # powershell script to list agent pools
  - task: PowerShell@2
    displayName: "List Agent Pools"
    inputs:
      targetType: "inline"
      script: |
        $uri = "$(System.TeamFoundationCollectionUri)$(System.TeamProject)/_apis/distributedtask/queues?api-version=6.0-preview.1"
        $headers = @{
          Authorization = "Basic $(System.AccessToken)"
        }
        $response = Invoke-RestMethod -Uri $uri -Method Get -Headers $headers
        Write-Host "##vso[task.setvariable variable=agentPools]$($response.value | ConvertTo-Json)"
