# hello world pipeline
# This pipeline deploys an agent pool on AKS
# using the az-selfhosted-agents helm chart

trigger: none

pool:
  #vmImage: "ubuntu-latest"
  name: KubernetesPoolWindows

parameters:
  - name: instanceNumber
    type: string
    default: "001"
    displayName: "Instance Number"
  - name: osType
    type: string
    default: "Linux"
    displayName: "Agent Pool OS Type"
    values:
      - Linux
      - Windows

variables:
  - group: ADO_k8s_agent_pool_vars
  - name: instanceNumber
    value: ${{ parameters.instanceNumber }}
  - name: kubernetesServiceEndpoint
    value: ADO_workload-cluster-012
  - name: linuxPoolName
    value: KubernetesLinuxPool${{ parameters.instanceNumber }}
  - name: windowsPoolName
    value: KubernetesWindowsPool${{ parameters.instanceNumber }}
  - name: linuxNamespace
    value: az-devops-linux-${{ parameters.instanceNumber }}
  - name: windowsNamespace
    value: az-devops-windows-${{ parameters.instanceNumber }}

stages:
  - stage: DeployAgentPool
    displayName: "Deploy Agent Pool on AKS"
    jobs:
      - deployment: DeployAgentPool
        displayName: "Deploy Agent Pool on AKS"
        environment: "ADO_k8s-agent-pool-${{ parameters.osType }}${{ parameters.instanceNumber }}"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                  persistCredentials: true
                # install prerequisites
                - task: PowerShell@2
                  displayName: "Install Prerequisites"
                  inputs:
                    targetType: "inline"
                    script: |
                      # install az cli
                      az config set extension.dynamic_install_allow_preview=true
                      # choco install base64
                      if (-not (Get-Command choco -ErrorAction SilentlyContinue)) {
                        iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
                      }
                      choco install base64
                    pwsh: true
                # kube login
                - task: Kubernetes@1
                  displayName: "kube login"
                  inputs:
                    connectionType: "Kubernetes Service Connection"
                    kubernetesServiceEndpoint: "$(kubernetesServiceEndpoint)"
                    command: "login"
                - task: Kubernetes@1
                  displayName: "Get AKS Nodes"
                  inputs:
                    connectionType: "Kubernetes Service Connection"
                    kubernetesServiceEndpoint: "$(kubernetesServiceEndpoint)"
                    command: "get"
                    arguments: "nodes -o wide"
                    secretType: "dockerRegistry"
                    containerRegistryType: "Azure Container Registry"
                    outputFormat: "none"
                # powershell script to deploy agent pool on aks
                - task: PowerShell@2
                  displayName: "Deploy Agent Pool on AKS"
                  inputs:
                    filePath: "infra/scripts/New-KubernetesAgentPool.ps1"
                    arguments: '-organizationUrl "$(System.CollectionUri)" -instanceNumber "$(instanceNumber)" -osType "${{ parameters.osType }}"'
                    pwsh: true
                  env:
                    AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
                - task: HelmDeploy@1
                  displayName: "helm list"
                  inputs:
                    connectionType: "Kubernetes Service Connection"
                    kubernetesServiceConnection: "$(kubernetesServiceEndpoint)"
                    command: "ls"
                    arguments: "--all-namespaces"
                # script to install keda
                - task: PowerShell@2
                  displayName: "Install Keda"
                  inputs:
                    filePath: "infra/scripts/Install-Keda.ps1"
                    pwsh: true
                # script to install az-selfhosted-agents helm chart
                - task: PowerShell@2
                  displayName: "Install az-selfhosted-agents"
                  inputs:
                    filePath: "helm-charts-v2/deployViaHelm.ps1"
                    arguments: '-instanceNumber "$(instanceNumber)" -organizationUrl "$(System.CollectionUri)" -linuxPoolName "$(linuxPoolName)" -windowsPoolName "$(windowsPoolName)" -dockerConfigJsonValueBase64 "$(dockerConfigJsonValueBase64)"'
                    pwsh: true
                    workingDirectory: "$(System.DefaultWorkingDirectory)/helm-charts-v2"
                  env:
                    AZURE_DEVOPS_EXT_PAT: $(AZURE_DEVOPS_EXT_PAT)
  - template: sample-run-on-linux-agent-k8s.template.yaml
    parameters:
      linuxPoolName: ${{ variables.linuxPoolName }}
      stageName: "DeployInParallelLinux${{ variables.instanceNumber }}"
      stageDisplayName: "Deploy in Parallel Linux (${{ variables.linuxPoolName }})"
  - template: sample-run-on-windows-agent-k8s.template.yaml
    parameters:
      windowsPoolName: ${{ variables.windowsPoolName }}
      stageName: "DeployInParallelWindows${{ variables.instanceNumber }}"
      stageDisplayName: "Deploy in Parallel Windows (${{ variables.windowsPoolName }})"
