# Local helper: render helm-charts-v2/az-selfhosted-agents with the same values override generated by pipeline
param(
  [string]$acr = 'cragentssgvhe4aipy37o',
  [string]$inst = '003',
  [string]$variant = 'docker'
)
$ErrorActionPreference = 'Stop'
$linuxRepo = switch($variant){ 'ubuntu22' { "$acr.azurecr.io/linux-sh-agent-ubuntu22" } 'dind' { "$acr.azurecr.io/linux-sh-agent-dind" } default { "$acr.azurecr.io/linux-sh-agent-docker" } }
$winRepo = "$acr.azurecr.io/windows-sh-agent-2022"
$enabledLinux = 'true'
$enabledWindows = 'false'
$yamlLines = @()
$yamlLines += 'linux:'
$yamlLines += ('  enabled: ' + $enabledLinux)
$yamlLines += '  image:'
$yamlLines += ('    repository: ' + $linuxRepo)
$yamlLines += "    tag: latest"
$yamlLines += 'windows:'
$yamlLines += ('  enabled: ' + $enabledWindows)
$yamlLines += '  image:'
$yamlLines += ('    repository: ' + $winRepo)
$yamlLines += "    tag: latest"
$yamlLines += 'common:'
$yamlLines += ('  instance: ' + $inst)
$yamlLines += ('linuxNamespace: az-devops-linux-' + $inst)
$yamlLines += ('windowsNamespace: az-devops-windows-' + $inst)
$yamlPath = Join-Path $PWD 'tmp-helm-values.yaml'
$yamlLines | Out-File -FilePath $yamlPath -Encoding utf8
Write-Host "Wrote temp values to $yamlPath"
$chartPath = Join-Path $PWD 'helm-charts-v2/az-selfhosted-agents'
if(-not (Test-Path $chartPath)){ Write-Error "Chart path $chartPath not found"; exit 2 }
# Render
helm template test-release $chartPath -f $yamlPath | Select-String -Pattern 'image:' -Context 0,2 | ForEach-Object { Write-Host $_.Line }
Write-Host "Rendered using chart: $chartPath"
