trigger: none
pr: none

parameters:
  - name: instanceNumber
    type: string
    default: "__INSTANCE_NUMBER__"
  - name: os
    type: string
    default: "linux"
    values:
      - linux
      - windows
  - name: stageName
    type: string
    default: "DeployInParallel"
  - name: stageDisplayName
    type: string
    default: "Deploy in Parallel"
  - name: helloWaitSeconds
    type: number
    default: 180
  - name: useAzureLocal
    type: boolean
    default: false
  - name: windowsImageVariant
    type: string
    default: "docker"
    values:
      - docker
      - dind
  - name: windowsVersion
    type: string
    default: "2022"
    values:
      - "2019"
      - "2022"
      - "2025"

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}
    jobs:
      - job: RunParallelTests
        displayName: "Run parallel tests on selected pool"
        pool:
          ${{ if and(eq(parameters.os, 'linux'), parameters.useAzureLocal) }}:
            name: KubernetesPoolOnPremLinux${{ parameters.instanceNumber }}
          ${{ if and(eq(parameters.os, 'linux'), not(parameters.useAzureLocal)) }}:
            name: KubernetesPoolLinux${{ parameters.instanceNumber }}
          ${{ if and(eq(parameters.os, 'windows'), parameters.useAzureLocal) }}:
            name: KubernetesPoolOnPremWindows${{ parameters.instanceNumber }}
          ${{ if and(eq(parameters.os, 'windows'), not(parameters.useAzureLocal)) }}:
            name: KubernetesPoolWindows${{ parameters.instanceNumber }}
        strategy:
          parallel: 5
        steps:
          - checkout: self
            persistCredentials: true
          - ${{ if eq(parameters.os, 'linux') }}:
              - task: PowerShell@2
                displayName: Verify PowerShell & az CLI (Linux)
                inputs:
                  targetType: inline
                  pwsh: true
                  script: |
                    Set-StrictMode -Version Latest
                    $ErrorActionPreference = 'Stop'
                    Write-Host "PowerShell version: $($PSVersionTable.PSVersion.ToString())"
                    if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
                        throw 'az CLI executable not found in PATH.'
                    }
                    $azInfoRaw = az version --output json --only-show-errors
                    if (-not $azInfoRaw) {
                        throw 'az version returned no output.'
                    }
                    $azInfo = $azInfoRaw | ConvertFrom-Json
                    $coreVersion = $null
                    if ($azInfo.PSObject.Properties.Name -contains 'core') {
                        $coreVersion = $azInfo.core
                    }
                    elseif ($azInfo.PSObject.Properties.Name -contains 'azure-cli-core') {
                        $coreVersion = $azInfo.'azure-cli-core'
                    }

                    if (-not $coreVersion) {
                        throw "az CLI version payload missing 'core' or 'azure-cli-core' property. Raw payload: $azInfoRaw"
                    }

                    Write-Host "az CLI core version: $coreVersion"
                    if ($azInfo.PSObject.Properties.Name -contains 'azure-cli-ml') {
                        Write-Host "azure-cli-ml extension version: $($azInfo.'azure-cli-ml')"
                    }
              - template: ../scripts/kubernetes/linux/hello-world.yml
                parameters:
                  helloWaitSeconds: ${{ parameters.helloWaitSeconds }}
          - ${{ if eq(parameters.os, 'windows') }}:
              - task: PowerShell@2
                displayName: Verify PowerShell & az CLI (Windows)
                inputs:
                  targetType: inline
                  pwsh: false
                  script: |
                    Set-StrictMode -Version Latest
                    $ErrorActionPreference = 'Stop'

                    Write-Host "PowerShell version: $($PSVersionTable.PSVersion.ToString())"

                    $pwsh = Get-Command pwsh -ErrorAction SilentlyContinue
                    if ($pwsh) {
                        try {
                            $pwshVersion = & $pwsh.Source -NoLogo -NoProfile -Command '$PSVersionTable.PSVersion.ToString()'
                            Write-Host "pwsh version: $pwshVersion"
                        }
                        catch {
                            Write-Warning "pwsh detected at $($pwsh.Source) but version check failed: $_"
                        }
                    }
                    else {
                        Write-Warning 'pwsh.exe not found in PATH. Skipping pwsh version check.'
                    }

                    $azCli = Get-Command az -ErrorAction SilentlyContinue
                    if (-not $azCli) {
                        Write-Warning 'az CLI executable not found in PATH. Skipping az version check.'
                        return
                    }

                    $azInfoRaw = & $azCli.Source version --output json --only-show-errors
                    if (-not $azInfoRaw) {
                        throw 'az version returned no output.'
                    }

                    $azInfo = $azInfoRaw | ConvertFrom-Json
                    $coreVersion = $null
                    if ($azInfo.PSObject.Properties.Name -contains 'core') {
                        $coreVersion = $azInfo.core
                    }
                    elseif ($azInfo.PSObject.Properties.Name -contains 'azure-cli-core') {
                        $coreVersion = $azInfo.'azure-cli-core'
                    }

                    if (-not $coreVersion) {
                        throw "az CLI version payload missing 'core' or 'azure-cli-core' property. Raw payload: $azInfoRaw"
                    }

                    Write-Host "az CLI core version: $coreVersion"

                    if ($azInfo.PSObject.Properties.Name -contains 'azure-cli-ml') {
                        Write-Host "azure-cli-ml extension version: $($azInfo.'azure-cli-ml')"
                    }
              - ${{ if and(eq(parameters.windowsImageVariant, 'dind'), eq(parameters.useAzureLocal, true)) }}:
                  - task: PowerShell@2
                    displayName: Docker DinD smoke test (Windows - AKS-HCI only)
                    inputs:
                      targetType: inline
                      pwsh: false
                      script: |
                        Set-StrictMode -Version Latest
                        $ErrorActionPreference = 'Stop'

                        Write-Host "Windows DinD smoke test (AKS-HCI/Azure Local only)"
                        Write-Host "Note: This test is skipped on standard AKS as Windows DinD is not supported there."

                        $dockerCmd = Get-Command docker -ErrorAction SilentlyContinue
                        if (-not $dockerCmd) {
                            throw 'docker.exe not found in PATH. Windows DinD agents should include the Docker CLI.'
                        }

                        $pipePath = '\\.\pipe\docker_engine'

                        Write-Host "Checking for Docker daemon access via named pipe: $pipePath"
                        if (-not (Test-Path $pipePath)) {
                            Write-Error "Docker engine pipe '$pipePath' not found. This Windows DinD agent should have the host Docker pipe mounted."
                            Write-Host "Troubleshooting info:"
                            Write-Host "- Ensure Docker Engine is installed on the Windows host node"
                            Write-Host "- Verify Helm values have windows.dind.enabled: true"
                            Write-Host "- Check volume mount in deployment: kubectl get deployment -n <namespace> -o yaml | Select-String docker"
                            throw "Docker engine pipe not available. Cannot proceed with DinD smoke test."
                        }

                        Write-Host "✓ Docker engine pipe found at $pipePath"
                        Write-Host "Docker CLI executable detected at $($dockerCmd.Source)"
                        & $dockerCmd.Source version
                        if ($LASTEXITCODE -ne 0) {
                            throw "docker version failed with exit code $LASTEXITCODE"
                        }

                        $map = @{
                            '2019' = 'mcr.microsoft.com/windows/nanoserver:1809'
                            '2022' = 'mcr.microsoft.com/windows/nanoserver:ltsc2022'
                            '2025' = 'mcr.microsoft.com/windows/nanoserver:ltsc2025'
                        }

                        $windowsVersion = '${{ parameters.windowsVersion }}'
                        if ([string]::IsNullOrWhiteSpace($windowsVersion)) { $windowsVersion = '2022' }
                        $testImage = $map[$windowsVersion]
                        if (-not $testImage) { $testImage = 'mcr.microsoft.com/windows/nanoserver:ltsc2022' }

                        Write-Host "Using Docker test image '$testImage' for windowsVersion=$windowsVersion"

                        & $dockerCmd.Source pull $testImage
                        if ($LASTEXITCODE -ne 0 -and $windowsVersion -eq '2025') {
                            Write-Warning "docker pull failed for $testImage (windowsVersion=$windowsVersion); attempting fallback to nanoserver:ltsc2022"
                            $testImage = 'mcr.microsoft.com/windows/nanoserver:ltsc2022'
                            & $dockerCmd.Source pull $testImage
                        }
                        if ($LASTEXITCODE -ne 0) {
                            throw "docker pull failed for $testImage"
                        }

                        & $dockerCmd.Source run --rm $testImage cmd.exe /c "echo Windows DinD smoke test"
                        if ($LASTEXITCODE -ne 0) {
                            throw "docker run failed for $testImage"
                        }

                        Write-Host "✓ Docker DinD smoke test completed successfully for $testImage"
                        Write-Host "✓ Windows DinD agent can access host Docker daemon via named pipe"
              - template: ../scripts/kubernetes/windows/hello-world.yml
                parameters:
                  helloWaitSeconds: ${{ parameters.helloWaitSeconds }}
