## Sample pipeline: run a short test job on a self-hosted agent pool created by the deploy pipeline
## Usage: queue this pipeline and pass parameters.instanceNumber (e.g. 003) and parameters.os (linux|windows)
## NOTE: Before queuing this pipeline you MUST authorize it to use the target agent pool.
##   - UI: Project settings -> Agent pools -> <pool> -> Security -> grant the Project Build Service 'Use' permission
##   - Or: authorize the pipeline in the pipeline's pipeline resources / environment settings

trigger: none
pr: none

parameters:
  - name: instanceNumber
    type: string
    default: "003"
  - name: os
    type: string
    default: "linux"
    values:
      - linux
      - windows

stages:
  - stage: RunOnSelfHosted
    displayName: Run sample job on self-hosted agent pool
    jobs:
      - job: RunSample
        displayName: Run simple test on self-hosted agent
        # select pool by OS parameter; this pipeline must be authorized to use the referenced pool
        pool:
          ${{ if eq(parameters.os, 'linux') }}:
            name: KubernetesPoolLinux${{ parameters.instanceNumber }}
          ${{ if eq(parameters.os, 'windows') }}:
            name: KubernetesPoolWindows${{ parameters.instanceNumber }}
        steps:
          - ${{ if eq(parameters.os, 'linux') }}:
            - script: |
                echo "Hello from self-hosted Linux agent"
                echo "Agent name: $(Agent.Name)"
                echo "Agent OS: $(Agent.OS)"
                echo "Agent Version: $(Agent.Version)"
                echo "Pool (parameter): ${{ parameters.os }} / instance ${{ parameters.instanceNumber }}"
              displayName: Print agent info (Linux)
            - bash: |
                # Demonstrate a simple command that validates container socket mounting
                if [ -e /var/run/docker.sock ]; then echo '/var/run/docker.sock is present'; else echo '/var/run/docker.sock not present'; fi
              displayName: Quick runtime check (Linux)
          - ${{ if eq(parameters.os, 'windows') }}:
            - powershell: |
                Write-Host "Hello from self-hosted Windows agent"
                Write-Host "Agent name: $(Agent.Name)"
                Write-Host "Agent OS: $(Agent.OS)"
                Write-Host "Agent Version: $(Agent.Version)"
                Write-Host "Pool (parameter): ${{ parameters.os }} / instance ${{ parameters.instanceNumber }}"
              displayName: Print agent info (Windows)
            - powershell: |
                # Skipping docker.sock check on Windows. You can check Docker Desktop or service state if needed.
                Write-Host 'Skipping docker.sock check on Windows.'
              displayName: Quick runtime check (Windows)
