trigger: none

pool: KubernetesPoolLinux #agent-on-kubernetes

resources:
  repositories:
    - repository: templates
      displayname: templates from devops
      type: git
      name: Cad4DevOps/ADO_az-devops-agents-k8s
      ref: main

stages:
  - stage: Deploy
    jobs:
      - deployment: agentSetup
        environment: ADO_test_linux
        displayName: "Agent Setup"
        strategy:
          runOnce:
            deploy:
              steps:
                #Branch Checkout
                - checkout: self
                  persistCredentials: true

                # Hello World program
                - template: .azuredevops/scripts/kubernetes/linux/hello-world.yaml@templates
