trigger: none

parameters:
  - name: windowsPoolName
    type: string
    default: "KubernetesWindowsPool001"
    displayName: "Windows Pool Name"

pool:
  name: ${{ parameters.windowsPoolName }}
  # demands:
  #   - Agent.OS -equals Windows
  #   - Agent.Name -equals $(Agent.Name)
  #   - Agent.Version -equals $(Agent.Version)

stages:
  - stage: Deploy1
    displayName: Deploy in Parallel 1
    dependsOn: []
    jobs:
      - deployment: agentSetup
        environment: ADO_test_windows
        displayName: "Agent Setup"
        strategy:
          runOnce:
            deploy:
              steps:
                #Hello World From CMDLINE
                - template: ../scripts/kubernetes/windows/hello-world.yaml

                #Print Hostname from CMDLINE
                - template: ../scripts/kubernetes/windows/windows-hostname.yaml
  - stage: Deploy2
    displayName: Deploy in Parallel 2
    dependsOn: []
    jobs:
      - deployment: agentSetup
        environment: ADO_test_windows
        displayName: "Agent Setup"
        strategy:
          runOnce:
            deploy:
              steps:
                #Hello World From CMDLINE
                - template: ../scripts/kubernetes/windows/hello-world.yaml

                #Print Hostname from CMDLINE
                - template: ../scripts/kubernetes/windows/windows-hostname.yaml
  - stage: Deploy3
    displayName: Deploy in Parallel 3
    dependsOn: []
    jobs:
      - deployment: agentSetup
        environment: ADO_test_windows
        displayName: "Agent Setup"
        strategy:
          runOnce:
            deploy:
              steps:
                #Hello World From CMDLINE
                - template: ../scripts/kubernetes/windows/hello-world.yaml

                #Print Hostname from CMDLINE
                - template: ../scripts/kubernetes/windows/windows-hostname.yaml
  - stage: Deploy4
    displayName: Deploy in Parallel 4
    dependsOn: []
    jobs:
      - deployment: agentSetup
        environment: ADO_test_windows
        displayName: "Agent Setup"
        strategy:
          runOnce:
            deploy:
              steps:
                #Hello World From CMDLINE
                - template: ../scripts/kubernetes/windows/hello-world.yaml

                #Print Hostname from CMDLINE
                - template: ../scripts/kubernetes/windows/windows-hostname.yaml
