trigger: none

parameters:
  - name: windowsPoolName
    type: string
    default: "KubernetesWindowsPool001"
    displayName: "Windows Pool Name"

stages:
  - template: sample-run-on-windows-agent-k8s.template.yaml
    parameters:
      windowsPoolName: ${{ parameters.windowsPoolName }}
      stageName: "DeployInParallelWindows"
      stageDisplayName: "Deploy in Parallel Windows (${{ parameters.windowsPoolName }})"
