parameters:
  - name: linuxPoolName
    type: string
    default: "KubernetesLinuxPool001"
    displayName: "Linux Pool Name"
  - name: stageName
    type: string
    default: "DeployInParallelLinux"
    displayName: "Stage Name"
  - name: stageDisplayName
    type: string
    default: "Deploy in Parallel Linux"
    displayName: "Stage Display Name"

stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}
    pool:
      name: ${{ parameters.linuxPoolName }}
      # demands:
      #   - Agent.OS -equals Linux
      #   - Agent.Name -equals $(Agent.Name)
      #   - Agent.Version -equals $(Agent.Version)
    jobs:
      - job: parallelTest1
        displayName: "Linux Parallel Test 1"
        steps:
          #Branch Checkout
          - checkout: self
            persistCredentials: true

          # Hello World program
          - template: ../scripts/kubernetes/linux/hello-world.yaml #@templates

          # test docker
          - task: CmdLine@2
            displayName: test docker
            inputs:
              script: |
                echo Write your commands here

                echo Hello world

                docker -v
      - job: parallelTest2
        displayName: "Linux Parallel Test 2"
        steps:
          #Branch Checkout
          - checkout: self
            persistCredentials: true

          # Hello World program
          - template: ../scripts/kubernetes/linux/hello-world.yaml #@templates

          # test docker
          - task: CmdLine@2
            displayName: test docker
            inputs:
              script: |
                echo Write your commands here

                echo Hello world

                docker -v
      - job: parallelTest3
        displayName: "Linux Parallel Test 3"
        steps:
          #Branch Checkout
          - checkout: self
            persistCredentials: true

          # Hello World program
          - template: ../scripts/kubernetes/linux/hello-world.yaml #@templates

          # test docker
          - task: CmdLine@2
            displayName: test docker
            inputs:
              script: |
                echo Write your commands here

                echo Hello world

                docker -v
      - job: parallelTest4
        displayName: "Linux Parallel Test 4"
        steps:
          #Branch Checkout
          - checkout: self
            persistCredentials: true

          # Hello World program
          - template: ../scripts/kubernetes/linux/hello-world.yaml #@templates

          # test docker
          - task: CmdLine@2
            displayName: test docker
            inputs:
              script: |
                echo Write your commands here

                echo Hello world

                docker -v
      - job: parallelTest5
        displayName: "Linux Parallel Test 5"
        steps:
          #Branch Checkout
          - checkout: self
            persistCredentials: true

          # Hello World program
          - template: ../scripts/kubernetes/linux/hello-world.yaml #@templates

          # test docker
          - task: CmdLine@2
            displayName: test docker
            inputs:
              script: |
                echo Write your commands here

                echo Hello world

                docker -v
