trigger: none

parameters:
  - name: linuxPoolName
    type: string
    default: "KubernetesLinuxPool001"
    displayName: "Linux Pool Name"

# resources:
#   repositories:
#     - repository: templates
#       displayname: templates from devops
#       type: git
#       name: Cad4DevOps/ADO_az-devops-agents-k8s
#       ref: main

stages:
  - template: sample-run-on-linux-agent-k8s.template.yaml
    parameters:
      linuxPoolName: ${{ parameters.linuxPoolName }}
      stageName: "DeployInParallelLinux"
      stageDisplayName: "Deploy in Parallel Linux (${{ parameters.linuxPoolName }})"
