trigger: none

pool:
  name: KubernetesPoolWindows # agent-on-kubernetes
  vmImage: azsh-windows-6c599c9f48-n2hxt # Windows agent pool specified!!!

stages:
  - stage: Deploy
    jobs:
      - deployment: agentSetup
        environment: ADO_test_windows
        displayName: "Agent Setup"
        strategy:
          runOnce:
            deploy:
              steps:
                #Hello World From CMDLINE
                - template: ../scripts/kubernetes/windows/hello-world.yaml

                #Print Hostname from CMDLINE
                - template: ../scripts/kubernetes/windows/windows-hostname.yaml
