# Uninstall self-hosted agents (Helm-based)
# - Helm uninstall agent release
# - Optionally uninstall KEDA (helm uninstall) and remove KEDA CRDs
# - Delete linux/windows namespaces
# - Optionally delete Azure DevOps agent pools

trigger: none
pr: none

parameters:
  - name: removeLinux
    type: boolean
    default: true
    displayName: Remove Linux namespace & resources
  - name: removeWindows
    type: boolean
    default: true
    displayName: Remove Windows namespace & resources
  - name: deleteAgentPools
    type: boolean
    default: true
    displayName: Delete corresponding Azure DevOps agent pools
  - name: removeKeda
    type: boolean
    default: true
    displayName: Uninstall KEDA and remove CRDs
  - name: instanceNumber
    type: string
    default: "003"
    displayName: Instance number suffix (e.g. 003)
  - name: AZURE_SERVICE_CONNECTION
    type: string
    default: "SvcConnRgScopedProd"
    values:
      - "SvcConnRgScopedProd"
  - name: ACR_NAME
    type: string
    default: "cragents0036o3yuvhlr3ygc"
    values:
      - "cragents0036o3yuvhlr3ygc"
  - name: useAzureLocal
    type: boolean
    default: false
  - name: aksResourceGroup
    type: string
    default: "rg-aks-ado-agents-003"
  - name: aksClusterName
    type: string
    default: "aks-ado-agents-003"
  - name: azureDevOpsOrgUrl
    type: string
    default: "https://dev.azure.com/devops-halo"
  - name: confirmDeletion
    type: string
    default: "YES"
    displayName: Type YES to actually perform deletions
  - name: bootstrapPoolName
    type: string
    default: "KubernetesPoolWindows"
  - name: kubeconfigAzureLocal
    type: string
    default: "workload-cluster-003-kubeconfig.yaml"
    displayName: Kubeconfig file name to use in Azure-local mode
  - name: kubeContextAzureLocal
    type: string
    default: "workload-cluster-003-admin@workload-cluster-003"
    displayName: Kube context name to verify in Azure-local mode
  - name: kubeConfigSecretFile
    type: string
    default: "AKS_workload-cluster-003-kubeconfig_file"
  - name: useOnPremAgents
    type: boolean
    default: false # Set to true to use on-premises agents, false to use cloud agents

variables:
  - group: "DevOpsAgentswithK8S-003" # to get AZDO_PAT
  - name: azureSubscription
    value: ${{ parameters.AZURE_SERVICE_CONNECTION }}

stages:
  - stage: UninstallHelm
    displayName: Uninstall (Helm + namespaces + KEDA cleanup)
    jobs:
      - job: Uninstall
        displayName: Uninstall resources
        pool:
          ${{ if eq(parameters.useAzureLocal, false) }}:
            ${{ if eq(parameters.useOnPremAgents, true) }}:
              name: UbuntuLatestPoolOnPrem
            ${{ else }}:
              vmImage: ubuntu-latest
          ${{ else }}:
            ${{ if ne(parameters.bootstrapPoolName, '') }}:
              name: ${{ parameters.bootstrapPoolName }}
            ${{ else }}:
              name: WindowsLatestPoolOnPrem
        steps:
          - checkout: self

          - task: PowerShell@2
            displayName: Validate confirmation
            inputs:
              targetType: inline
              pwsh: true
              script: |
                if('${{ parameters.confirmDeletion }}' -ne 'YES'){
                  Write-Error "confirmDeletion parameter must be 'YES' to proceed. Current: '${{ parameters.confirmDeletion }}'"
                } else { Write-Host 'Confirmation OK.' }

          - ${{ if eq(parameters.useAzureLocal, true) }}:
              - task: DownloadSecureFile@1
                name: DownloadKubeconfig
                displayName: Download AKS kubeconfig (secure file)
                inputs:
                  secureFile: ${{ parameters.kubeConfigSecretFile }}
          - ${{ if eq(parameters.useAzureLocal, false) }}:
              - task: AzureCLI@2
                displayName: Fetch AKS credentials (az aks get-credentials)
                inputs:
                  azureSubscription: $(azureSubscription)
                  scriptType: bash
                  scriptLocation: inlineScript
                  inlineScript: |
                    set -euo pipefail
                    if [ -z "${{ parameters.aksResourceGroup }}" ] || [ -z "${{ parameters.aksClusterName }}" ]; then
                      echo "AKS resource group or cluster name not provided. Provide aksResourceGroup and aksClusterName when useAzureLocal is false."
                      exit 1
                    fi
                    KCFG="$AGENT_TEMPDIRECTORY/kubeconfig"
                    echo "Fetching AKS credentials for ${{ parameters.aksClusterName }} in ${{ parameters.aksResourceGroup }} into $KCFG"
                    az aks get-credentials --resource-group "${{ parameters.aksResourceGroup }}" --name "${{ parameters.aksClusterName }}" --file "$KCFG" --overwrite-existing
                    echo "##vso[task.setvariable variable=KUBECONFIG]$KCFG"

          - ${{ if eq(parameters.useAzureLocal, true) }}:
              - task: PowerShell@2
                displayName: Prepare kubeconfig & ensure kubectl (secure file)
                inputs:
                  targetType: inline
                  pwsh: true
                  script: |
                    Set-StrictMode -Version Latest
                    $ErrorActionPreference = 'Stop'
                    $secureKubeConfig = '$(DownloadKubeconfig.secureFilePath)'
                    if([string]::IsNullOrEmpty($secureKubeConfig)){
                      throw 'DownloadSecureFile did not produce a path. Ensure the task name is DownloadKubeconfig and useAzureLocal is true.'
                    }
                    $kubeconfigPath = Join-Path $env:AGENT_TEMPDIRECTORY 'kubeconfig'
                    Copy-Item -Path $secureKubeConfig -Destination $kubeconfigPath -Force
                    Write-Host "Copied kubeconfig to $kubeconfigPath"
                    Write-Host "##vso[task.setvariable variable=KUBECONFIG]$kubeconfigPath"
                    $kubectlCmd = Get-Command kubectl -ErrorAction SilentlyContinue
                    if(-not $kubectlCmd){
                      Write-Host 'kubectl not found on PATH; downloading...'
                      $url = 'https://dl.k8s.io/release/v1.29.4/bin/linux/amd64/kubectl'
                      $kubectlPath = Join-Path $env:AGENT_TEMPDIRECTORY 'kubectl'
                      Invoke-WebRequest -Uri $url -OutFile $kubectlPath
                      chmod +x $kubectlPath
                      Write-Host "##vso[task.prependpath]$($env:AGENT_TEMPDIRECTORY)"
                      Write-Host "Downloaded kubectl to $kubectlPath and prepended AGENT_TEMPDIRECTORY to PATH"
                    } else { Write-Host "kubectl found at $($kubectlCmd.Path)" }
          - ${{ if eq(parameters.useAzureLocal, false) }}:
              - task: PowerShell@2
                displayName: Prepare kubeconfig & ensure kubectl (AKS credentials)
                inputs:
                  targetType: inline
                  pwsh: true
                  script: |
                    Set-StrictMode -Version Latest
                    $ErrorActionPreference = 'Stop'
                    # When useAzureLocal is false the previous AzureCLI step exported KUBECONFIG via pipeline variable
                    $kubeconfigPath = $env:KUBECONFIG
                    if([string]::IsNullOrEmpty($kubeconfigPath) -or -not (Test-Path $kubeconfigPath)){
                      throw "KUBECONFIG not set or file not found. Ensure the AzureCLI step that fetched AKS credentials ran successfully. KUBECONFIG='$kubeconfigPath'"
                    }
                    Write-Host "Using kubeconfig at $kubeconfigPath"
                    # Ensure kubectl is available or download it to AGENT_TEMPDIRECTORY
                    $kubectlCmd = Get-Command kubectl -ErrorAction SilentlyContinue
                    if(-not $kubectlCmd){
                      Write-Host 'kubectl not found on PATH; downloading...'
                      $url = 'https://dl.k8s.io/release/v1.29.4/bin/linux/amd64/kubectl'
                      $kubectlPath = Join-Path $env:AGENT_TEMPDIRECTORY 'kubectl'
                      Invoke-WebRequest -Uri $url -OutFile $kubectlPath
                      chmod +x $kubectlPath
                      Write-Host "##vso[task.prependpath]$($env:AGENT_TEMPDIRECTORY)"
                      Write-Host "Downloaded kubectl to $kubectlPath and prepended AGENT_TEMPDIRECTORY to PATH"
                    } else { Write-Host "kubectl found at $($kubectlCmd.Path)" }

          - task: HelmInstaller@1
            displayName: Install Helm client
            enabled: false
            inputs:
              helmVersionToInstall: "stable"

          - task: PowerShell@2
            displayName: Uninstall resources (via repo script)
            env:
              KUBECONFIG: $(KUBECONFIG)
              AZDO_PAT: $(AZDO_PAT)
            inputs:
              targetType: inline
              pwsh: true
              script: |
                Set-StrictMode -Version Latest
                $ErrorActionPreference = 'Stop'
                $scriptPath = '$(Build.SourcesDirectory)\\uninstall-selfhosted-agents-helm.ps1'
                if(-not (Test-Path $scriptPath)){
                  Write-Error "Uninstall helper script not found at $scriptPath"
                }
                # Build a parameter hashtable and splat it to preserve types (booleans as $true/$false)
                $params = @{}
                $params.Kubeconfig = "$(KUBECONFIG)"
                $params.InstanceNumber = '${{ parameters.instanceNumber }}'
                $params.AzureDevOpsOrgUrl = '${{ parameters.azureDevOpsOrgUrl }}'
                $params.AzDevOpsToken = $env:AZDO_PAT
                if ('${{ parameters.removeLinux }}' -eq 'True') { $params.RemoveLinux = $true }
                if ('${{ parameters.removeWindows }}' -eq 'True') { $params.RemoveWindows = $true }
                if ('${{ parameters.removeKeda }}' -eq 'True') { $params.RemoveKeda = $true }
                if ('${{ parameters.deleteAgentPools }}' -eq 'True') { $params.DeleteAgentPools = $true }
                if ('${{ parameters.useAzureLocal }}' -eq 'True') { $params.UseAzureLocal = $true }
                if ('${{ parameters.useAzureLocal }}' -eq 'True') {
                  $params.KubeconfigAzureLocal = '${{ parameters.kubeconfigAzureLocal }}'
                  $params.KubeContextAzureLocal = '${{ parameters.kubeContextAzureLocal }}'
                }
                $params.ConfirmDeletion = '${{ parameters.confirmDeletion }}'

                # Mask AZDO token for logging
                $maskedToken = if ($params.AzDevOpsToken) { '***' } else { '(none)' }
                $logParts = @(
                  "-Kubeconfig $($params.Kubeconfig)",
                  "-InstanceNumber $($params.InstanceNumber)",
                  "-AzureDevOpsOrgUrl $($params.AzureDevOpsOrgUrl)",
                  "-AzDevOpsToken $maskedToken"
                )
                if ($params.RemoveLinux) { $logParts += '-RemoveLinux' }
                if ($params.RemoveWindows) { $logParts += '-RemoveWindows' }
                if ($params.RemoveKeda) { $logParts += '-RemoveKeda' }
                if ($params.DeleteAgentPools) { $logParts += '-DeleteAgentPools' }
                if ('${{ parameters.useAzureLocal }}' -eq 'True') { $logParts += '-UseAzureLocal' }
                if ('${{ parameters.useAzureLocal }}' -eq 'True' -and '${{ parameters.kubeconfigAzureLocal }}' -ne '') { $logParts += ('-KubeconfigAzureLocal ' + $params.KubeconfigAzureLocal) }
                if ('${{ parameters.useAzureLocal }}' -eq 'True' -and '${{ parameters.kubeContextAzureLocal }}' -ne '') { $logParts += ('-KubeContextAzureLocal ' + $params.KubeContextAzureLocal) }
                $logParts += "-ConfirmDeletion $($params.ConfirmDeletion)"

                Write-Host "Invoking uninstall script: $scriptPath with args: $($logParts -join ' ')"
                & "$scriptPath" @params

      - job: Summary
        displayName: Uninstall Summary
        dependsOn: Uninstall
        condition: always()
        pool:
          ${{ if parameters.useOnPremAgents }}:
            name: UbuntuLatestPoolOnPrem
          ${{ else }}:
            vmImage: ubuntu-latest
        steps:
          - task: PowerShell@2
            displayName: Summarize uninstall
            inputs:
              targetType: inline
              pwsh: true
              script: |
                $inst='${{ parameters.instanceNumber }}'
                $lines = @('# Uninstall Summary','',"Instance: $inst",'','Requested:','- removeLinux: ${{ parameters.removeLinux }}','- removeWindows: ${{ parameters.removeWindows }}','- removeKeda: ${{ parameters.removeKeda }}','- deleteAgentPools: ${{ parameters.deleteAgentPools }}')
                $path = Join-Path $env:SYSTEM_DEFAULTWORKINGDIRECTORY uninstall-helm-summary.md
                $lines | Out-File $path -Encoding utf8
                Write-Host "##vso[task.addattachment type=Distributedtask.Core.Summary;name=Uninstall Summary]$path"
                $lines | ForEach-Object { Write-Host $_ }
