{{- if .Values.linux.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: pipeline-auth
  namespace: {{ .Values.linuxNamespace }}
data:
  personalAccessToken: {{ .Values.secretlinux.data.AZP_TOKEN_VALUE }}
