apiVersion: v1
data:
  AZP_POOL: {{ .Values.secretlinux.data.AZP_POOL_VALUE }}
  AZP_TOKEN: {{ .Values.secretlinux.data.AZP_TOKEN_VALUE }}
  AZP_URL: {{ .Values.secretlinux.data.AZP_URL_VALUE }}
kind: Secret
metadata:
  name: {{ .Values.secretlinux.name }}
  namespace: {{ .Values.linuxNamespace }}
  labels:
    {{- include "az-selfhosted-agents.labels" . | nindent 4 }}
type: Opaque