{{- $v := .Values.regsecret.data.DOCKER_CONFIG_JSON_VALUE | default "" }}
{{- if and $v (ne $v "") }}
apiVersion: v1
{{- if regexMatch "^[A-Za-z0-9+/=]{16,}$" $v }}
data:
  .dockerconfigjson: {{ $v | quote }}
{{- else }}
stringData:
  .dockerconfigjson: {{ $v | quote }}
{{- end }}
kind: Secret
metadata:
  name: regsecret
  namespace: {{ .Values.linuxNamespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}
