apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.regsecret.data.DOCKER_CONFIG_JSON_VALUE }}
kind: Secret
metadata:
  name: regsecret
  namespace: {{ .Values.windowsNamespace }}
type: kubernetes.io/dockerconfigjson
