apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: install-docker-windows
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: docker-installer
  template:
    metadata:
      labels:
        app: docker-installer
    spec:
      hostNetwork: true
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
      - key: "sku"
        operator: "Equal"
        value: "Windows"
        effect: "NoSchedule"
      containers:
      - name: installer
        image: mcr.microsoft.com/powershell:lts-7.4-windowsservercore-ltsc2022
        command:
        - C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        - -NoLogo
        - -NoProfile
        - -Command
        args:
        - |
          Set-StrictMode -Version Latest
          $ErrorActionPreference = 'Stop'
          [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
          
          Write-Host "=== Docker Installation Script for AKS Windows Nodes ==="
          Write-Host "Node: $env:COMPUTERNAME"
          Write-Host "Date: $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
          
          # Check if Docker is already installed
          Write-Host "`nChecking for existing Docker installation..."
          $dockerSvc = Get-Service -Name docker,com.docker.service,moby-engine -ErrorAction SilentlyContinue | Select-Object -First 1
          
          if ($dockerSvc) {
              Write-Host "Docker service found: $($dockerSvc.Name) (Status: $($dockerSvc.Status))"
              if ($dockerSvc.Status -ne 'Running') {
                  Write-Host "Starting Docker service..."
                  Start-Service $dockerSvc.Name -ErrorAction SilentlyContinue
              }
              Write-Host "Docker is already installed and configured."
              Write-Host "Installation script will now sleep to keep the DaemonSet pod running."
              Start-Sleep -Seconds 86400
              exit 0
          }
          
          Write-Host "Docker not found. Beginning installation..."
          
          # Download and run the official Docker installation script
          $installerUrl = "https://raw.githubusercontent.com/microsoft/Windows-Containers/Main/helpful_tools/Install-DockerCE/install-docker-ce.ps1"
          $installerPath = Join-Path $env:TEMP "install-docker-ce.ps1"
          
          Write-Host "Downloading Docker installer from: $installerUrl"
          try {
              Invoke-WebRequest -UseBasicParsing -Uri $installerUrl -OutFile $installerPath -ErrorAction Stop
              Write-Host "Download complete: $installerPath"
          }
          catch {
              Write-Error "Failed to download Docker installer: $_"
              Start-Sleep -Seconds 300
              exit 1
          }
          
          Write-Host "`nRunning Docker installer..."
          try {
              & $installerPath
              if ($LASTEXITCODE -ne 0) {
                  throw "Docker installer exited with code $LASTEXITCODE"
              }
          }
          catch {
              Write-Error "Docker installation failed: $_"
              Start-Sleep -Seconds 300
              exit 1
          }
          finally {
              Remove-Item -Path $installerPath -Force -ErrorAction SilentlyContinue
          }
          
          # Verify installation
          Write-Host "`nVerifying Docker installation..."
          $dockerSvc = Get-Service -Name docker,com.docker.service,moby-engine -ErrorAction SilentlyContinue | Select-Object -First 1
          
          if ($dockerSvc) {
              Write-Host "✓ Docker service installed: $($dockerSvc.Name)"
              if ($dockerSvc.Status -eq 'Running') {
                  Write-Host "✓ Docker service is running"
              }
              else {
                  Write-Host "Starting Docker service..."
                  Start-Service $dockerSvc.Name
                  Write-Host "✓ Docker service started"
              }
              
              # Check for Docker CLI
              $dockerExe = Get-Command docker.exe -ErrorAction SilentlyContinue
              if ($dockerExe) {
                  Write-Host "✓ Docker CLI found at: $($dockerExe.Source)"
                  try {
                      $dockerVersion = & docker.exe version --format '{{.Server.Version}}'
                      Write-Host "✓ Docker version: $dockerVersion"
                  }
                  catch {
                      Write-Warning "Docker CLI present but version check failed: $_"
                  }
              }
              
              # Check for named pipe
              $pipePath = '\\.\pipe\docker_engine'
              if (Test-Path $pipePath) {
                  Write-Host "✓ Docker named pipe exists: $pipePath"
              }
              else {
                  Write-Warning "Docker named pipe not yet available: $pipePath (may appear after restart)"
              }
              
              Write-Host "`n=== Docker Installation Complete ==="
              Write-Host "DinD agents can now use the Docker daemon on this node."
              Write-Host "Script will sleep to keep the DaemonSet pod running."
          }
          else {
              Write-Error "Docker installation completed but service not found!"
              Start-Sleep -Seconds 300
              exit 1
          }
          
          # Sleep indefinitely to keep the pod running
          Start-Sleep -Seconds 86400
        securityContext:
          windowsOptions:
            hostProcess: true
            runAsUserName: "NT AUTHORITY\\SYSTEM"
      terminationGracePeriodSeconds: 30
